### ISSUE TITLE
Versioning on the website is broken

### ISSUE THREAD

**Issue by Nekretaur** [neoforged/websites#12]
![image](https://github.com/neoforged/websites/assets/84230130/bf8d70a2-700c-40fb-acb4-d0c093bcad40)

**Comment by Technici4n** [comment]
Cache issue, will probably resolve itself.

**Comment by PlatinPython** [comment]
I mean, it's also broken in private mode 🤔

**Comment by Technici4n** [comment]
If you disable cache and reload it works again: (bottom right checkbox)
![image](https://github.com/neoforged/websites/assets/13494793/5cc626e7-238f-408a-92ca-0b314de1ae95)

🤔

**Comment by PlatinPython** [comment]
Yeah, that works. Also nice to know that exists.

**Comment by sciwhiz12** [comment]
I've purged the cache via the Cloudflare dashboard. It seems to work now, even in a Firefox private window.
