### ISSUE TITLE
Broken link in 20.2 Registry Rework blog post

### ISSUE THREAD

**Issue by rekitheduck** [neoforged/websites#19]
On the main website, the https://neoforged.net/news/20.2registry-rework/ blog post has a broken link to the `NeoForge 20.2 for Minecraft 1.20.2` page which leads to a 404 page

The link it has is https://neoforged.net/news/20.2release
when it should be https://neoforged.net/news/20.2release/

**Comment by Technici4n** [comment]
Thanks, fixed!
