### ISSUE TITLE
Add projects neoforge link to website

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/websites#22]
Can https://projects.neoforged.net/  be linked somewhere here? https://neoforged.net/
It such a useful tool to know what the neoforge version is for a mc version that it's annoying to have to hunt for it every time
![image](https://github.com/neoforged/websites/assets/40846040/c926848d-e942-48dc-8e9d-b4977105cb68)

There has been many people asking for the project versions and have to be told about the project page constantly.

**Comment by Technici4n** [comment]
Fixed in 3cfb86c.
