### ISSUE TITLE
"Latest News" contains all news items instead of just the latest few ones

### ISSUE THREAD

**Issue by IchHabeHunger54** [neoforged/websites#36]
As the title says. Since we already have a dedicated subpage listing all news items, I think it would be reasonable to actually only show the latest few items (latest three or something like that) on the main page, maybe with a "Read More" link that points to the news subpage.

Edit: This should probably also be extended to the "Recent Posts" section in the sidebar.

**Comment by UltimatChamp** [comment]
> This should probably also be extended to the "Recent Posts" section in the sidebar.

This only shows the latest 5.
