### ISSUE TITLE
Add a main menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [neoforged/websites#5]
It'd be a great to have a main menu with links to a news page, a FAQ, GitHub, and the Discord server

Like https://mainroad-demo.netlify.app/
![image](https://github.com/neoforged/websites/assets/51363864/2500e89d-921e-4c82-a31d-e5c70911db7c)

**Comment by UltimatChamp** [comment]
There's no need now. Since, the website doesn't have a large amount of content. There's currently only the homepage and the news page which can be found in the center.

**Comment by UltimatChamp** [comment]
First things like the installer menu and the search menu are focused. These items aren't that necessary, for now!

**Comment by UltimatChamp** [comment]
Moreover, they can be added into the sidebar or something. If they have to add these links, I don't think @cpw will want these items to get focused.

**Comment by UltimatChamp** [comment]
I'm talking about making them better :)! 

The installer section is not proper. <a href="https://github.com/neoforged/websites/pull/7">Check this-></a>
The search bar just redirects you to Google.
And more...!

Yes, but these items should still be added, maybe I will make a pull request, later!

**Comment by UltimatChamp** [comment]
> Last time I checked the website there was no link to the Discord at all which is where it appears most developer discussions are happening. These links don't necessarily need to be in a main menu but should at least be present on the website. One may expect the installer download to be on the homepage, and there's already a search bar in the sidebar.

The links have been added in https://github.com/neoforged/websites/commit/0e01c96808df4de4ee1f73107ca49b260acc79fe
